---
- name: Install Ruby and Bundler
  hosts: all
  become: true
  tasks:
    - name: Update repository cache
      apt: 
        update_cache: yes
    
    - name: Install ruby & bundler
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ruby-full
        - ruby-bundler
        - build-essential
